import { ingredientsList, IngredientType } from "./ingredints-data";

const routeToImg: string = "/img/"

export type RecipeType = {
    id: number,
    name: string,
    img: Base64URLString;
    favorite: boolean,
    categoryId: number,
    category: () => string,
    eatingTimeId: number,
    eatingTime: () => string,
    cookingTimeId: number,
    cookingTime: () => string, 
    difficultyId: number,
    difficulty: () => string,
    ingredients: IngredientType[],
    todoList: string,
}

// Функция которая достает игредиенты копируя их
export const getCopiedIngredientsByIds = (
    ingredientIds: number[]
  ): IngredientType[] => {
    return ingredientIds
      .map((id) => {
        const ingredient = ingredientsList.find((ing) => ing.id === id);
        return ingredient ? { ...ingredient } : null;
      })
      .filter((ing): ing is IngredientType => ing !== null);
  };

// Функция для подсчета ID категории (на будущее)
export const getCategory = (id: number): string => {
    switch (id) {
    case 1: return "Закуска"
    case 2: return "Первое блюдо"
    case 3: return "Второе блюдо"
    case 4: return "Напиток"
    case 5: return "Десерт"
    default: return "Другое"
  }
}

export const getEatingTime = (id: number): string => {
    switch (id) {
        case 1: return "Завтрак"
        case 2: return "Обед"
        case 3: return "Полдник"
        case 4: return "Ужин"
        default: return "В любое время"
    }
}

export const getCookingTime = (id: number): string => {
    switch (id) {
        case 1: return "Быстро (до 30 минут)"
        case 2: return "Долго (более 30 минут)"
        default: return "Неизвестно"
    }
}

export const getDifficulty = (id: number) => {
    switch (id) {
        case 1: return "Легко"
        case 2: return "Средне"
        case 3: return "Сложно"
        default: return "Любая"
    }
}

export const recipes: RecipeType[] = [
    {
        id: 0,
        name: "Бананы в шоколаде",
        img: routeToImg + 'bananas.jpg',
        favorite: false,
        categoryId: 5,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 3,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([100, 20, 1, 72]),
        todoList: '1) Бананы очистить и разрезать пополам. Если фрукты крупные — разрезать на три части.\n2) Насадить каждый кусочек банана на деревянную шпажку. Можно использовать палочки для суши, палочки для мороженого, шпажки для канапе или деревянные шампуры.\n3) Шоколад разломать на кусочки и выложить в глубокую миску. Установить миску с шоколадом на водяную баню (на кастрюлю с кипящей водой) так, чтобы вода не касалась дна миски. Слегка помешивая, растопить шоколад.\n4) Когда шоколад растопится, влить в миску молоко. Лопаткой соединить шоколад с молоком в однородную глазурь.\n5) Взять банан, насаженный на палочку, и намазать на него шоколадную глазурь со всех сторон.\n6) Посыпать банан, покрытый шоколадом, мелкой крошкой белого шоколада, кокосовой стружкой или кондитерской посыпкой по желанию.\n7) Поставить банан на палочке в стакан и подготовить следующий. Если палочки короткие, закрепить их в чём-то мягком.\n8) Когда глазурь подсохнет, выложить бананы на тарелку и поставить в холодильник на 1 час.\nДля десерта лучше брать крепкие, но спелые бананы.',
    },
    {
        id: 1,
        name: "Торт",
        img: routeToImg + 'cake.jpg',
        favorite: false,
        categoryId: 5,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 5,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([0, 6, 1, 27, 70]),
        todoList: 'Растереть яйцо с сахаром и мукой, добавить ванилин, влить молоко. Перемешать венчиком, поставить на медленный огонь, варить до загустения, постоянно мешая. Полностью остудить. Сливочное масло взбить миксером, постепенно добавляя остывшую заварную массу. Смешать яйцо с сахаром, добавить творог, ванилин, соду и постепенно ввести муку. Тесто должно получиться не совсем крутым, но плотным. Разделить на 6–8 частей. Тонко раскатать, наколоть вилкой, чтоб не вздувались. Печь до зарумянивания на сковороде с двух сторон. Обрезать неровные края. Остудить. Смазать коржи кремом, посыпать орехами и шоколадом',
    },
    {
        id: 2,
        name: "Мороженное",
        img: routeToImg + 'icycream.jpg',
        favorite: false,
        categoryId: 5,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 5,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([3, 1, 27, 106]),
        todoList: '1) Налить молоко в ковшик и довести до кипения. Сразу снять с огня, удалить пенку.\n2) Добавить обычный и ванильный сахар, перемешать, чтобы он полностью растворился.\n3) Дать остыть до комнатной температуры.\n4) Желтки взбить венчиком до получения массы однородной консистенции. Добавить в сладкое молоко. Снова взбить.\n5) Поместить ковшик на горячую водяную баню (большую кастрюлю с водой довести до кипения и оставить на огне). Постоянно помешивая венчиком, варить до загустения.\n6) Дать желтково-молочной массе остыть.\n7) Сливки взбить миксером до получения пышной плотной массы. Постепенно добавить их в кастрюлю, взбивая миксером на средней скорости.\n8) Переложить получившуюся массу в пластиковый контейнер. Убрать в морозильную камеру на 5 часов.\n9) Через каждый час доставать её и перемешивать. Это необходимо, чтобы в массе не образовывался лёд: тогда пломбир получится очень нежным.\nВажные моменты: молоко должно быть только натуральным, никакие обезжиренные варианты не подойдут. Сливки также необходимы натуральные коровьи, без загустителей и прочих добавок',
    },
    {
        id: 3,
        name: "Омлет",
        img: routeToImg + 'omlet.jpg',
        favorite: false,
        categoryId: 2,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 1,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 3,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([6, 2, 3, 5]),
        todoList: 'Чтобы приготовить омлет, начните с разбивания яиц в миску и добавления немного молока. Взбейте смесь венчиком до получения однородной массы. На сковороде разогрейте немного масла на среднем огне и вылейте яичную смесь. Дайте омлету немного схватиться по краям, а затем, с помощью лопатки, приподнимите их, позволяя жидким яйцам растекаться к краям. \nКогда омлет почти готов, но все еще немного мокроват, посолите и поперчите по вкусу, добавив при желании любимые начинки. Сложите омлет пополам и дайте ему приготовиться ещё несколько секунд до золотистой корочки. Затем аккуратно переложите омлет на тарелку и подавайте горячим. Приятного аппетита!',
    },
    {
        id: 4,
        name: "Гречневая каша",
        img: routeToImg + 'grechka.jpg',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 1,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([9, 4, 34, 27]),
        todoList: '1) Промыть гречку. 2) Залить водой в соотношении 1:2. 3) Варить 15-20 минут до готовности. 4) Добавить обжаренный лук.'
    },
    {
        id: 5,
        name: "Овощной суп",
        img: routeToImg + 'ovosh_sup.jpg',
        favorite: false,
        categoryId: 2,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 2,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([36, 37, 41, 34, 4, 35]),
        todoList: '1) Нарезать овощи. 2) Обжарить лук и морковь. 3) Добавить картофель и воду. 4) Варить 25 минут. 5) Добавить помидоры за 5 минут до готовности.'
    },
    {
        id: 6,
        name: "Салат Оливье",
        img: routeToImg + 'olivie.webp',
        favorite: false,
        categoryId: 1,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 5,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([6, 37, 40, 46, 31]),
        todoList: '1) Картофель, морковь и яйца отварить и нарезать кубиками.\n2) Огурцы нарезать кубиками.\n3) Смешать все ингредиенты. Добавить зеленый горошек, соль, перец и майонез.',
    },
    {
        id: 7,
        name: "Плов",
        img: routeToImg + 'plov.webp',
        favorite: false,
        categoryId: 2,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 3,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 3,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([8, 34, 37, 20, 4]),
        todoList: '1) Мясо нарезать кубиками и обжарить на сковороде.\n2) Добавить нарезанный лук и морковь.\n3) Всыпать рис и залить водой. Добавить соль, перец и специи.\n4) Тушить на медленном огне до готовности риса.',
    },
    {
        id: 8,
        name: "Блины",
        img: routeToImg + 'blini.jpg',
        favorite: false,
        categoryId: 1,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 1,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([0, 6, 3, 5, 70]),
        todoList: '1) Яйца взбить с сахаром, солью и молоком.\n2) Добавить муку и перемешать до однородной массы.\n3) Жарить на разогретой сковороде с обеих сторон до золотистого цвета.',
    },
    {
        id: 9,
        name: "Солянка",
        img: routeToImg + 'solyanka.jpg',
        favorite: false,
        categoryId: 2,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 2,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 3,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 3,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([96, 34, 41, 15, 4]),
        todoList: '1) Мясные деликатесы нарезать соломкой.\n2) Огурцы соленые и лук нарезать кубиками.\n3) Обжарить лук, добавить огурцы и томатную пасту.\n4) В кипящий бульон добавить мясные деликатесы, обжаренные овощи, оливки, лимон и каперсы.\n5) Варить 5-7 минут.',
    },
    {
        id: 10,
        name: "Винегрет",
        img: routeToImg + 'vinegret.png',
        favorite: false,
        categoryId: 1,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 3,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([15, 16, 26, 27]),
        todoList: '1) Свеклу, картофель и морковь отварить до готовности и нарезать кубиками.\n2) Соленые огурцы и лук нарезать кубиками.\n3) Смешать все ингредиенты и заправить растительным маслом.',
    },
    {
        id: 11,
        name: "Драники",
        img: routeToImg + 'draniki.jpg',
        favorite: false,
        categoryId: 1,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 1,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([28, 0, 29]),
        todoList: '1) Картофель очистить и натереть на крупной терке.\n2) Добавить яйцо, муку, соль и перец. Перемешать.\n3) Жарить на разогретой сковороде с обеих сторон до золотистого цвета.',
    },
        {
        id: 12,
        name: "Каша овсяная",
        img: routeToImg + 'ovsyanka.webp',
        favorite: false,
        categoryId: 1,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 1,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([30, 31, 32]),
        todoList: '1) Овсяные хлопья залить молоком или водой.\n2) Добавить соль, сахар и сливочное масло.\n3) Варить на медленном огне до готовности, помешивая.',
    },
    {
        id: 13,
        name: "Шашлык",
        img: routeToImg + 'shashlik.webp',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 2,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 3,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 3,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([18, 33, 34]),
        todoList: '1) Мясо нарезать кубиками.\n2) Добавить лук, соль, перец и специи. Перемешать и оставить мариноваться на несколько часов.\n3) Нанизать мясо на шампуры.\n4) Жарить на мангале до готовности, периодически переворачивая.',
    },
        {
        id: 14,
        name: "Суп гороховый",
        img: routeToImg + 'gorohoviy_sup.webp',
        favorite: false,
        categoryId: 2,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 3,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([35, 9, 4]),
        todoList: '1) Горох замочить на несколько часов или на ночь.\n2) Мясо залить водой и варить до готовности.\n3) Добавить нарезанный картофель, морковь и лук.\n4) Варить до готовности овощей. Добавить горох, соль, перец и специи.',
    },
    {
        id: 15,
        name: "Сырники",
        img: routeToImg + 'sirniki.webp',
        favorite: false,
        categoryId: 1,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 3,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([36, 0, 6]),
        todoList: '1) Творог смешать с яйцом, сахаром и мукой. Перемешать.\n2) Сформировать сырники.\n3) Жарить на разогретой сковороде с обеих сторон до золотистого цвета.',
    },
        {
        id: 16,
        name: "Запеканка картофельная",
        img: routeToImg + 'zapekanka.webp',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([9, 37, 38]),
        todoList: '1) Картофель отварить и нарезать кружочками.\n2) Лук нарезать полукольцами и обжарить.\n3) Форму для запекания смазать маслом.\n4) Выложить слоями картофель, лук и грибы. Залить сметаной и посыпать сыром.\n5) Запекать в духовке до золотистой корочки.',
    },
    {
        id: 17,
        name: "Шарлотка",
        img: routeToImg + 'sharlotka.webp',
        favorite: false,
        categoryId: 5,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([39, 0, 6]),
        todoList: '1) Яблоки нарезать кубиками.\n2) Яйца взбить с сахаром.\n3) Добавить муку и перемешать.\n4) Вылить тесто в форму для запекания, добавить яблоки.\n5) Запекать в духовке до готовности.',
    },
    {
        id: 18,
        name: "Тыквенный суп-пюре",
        img: routeToImg + 'pumpkin_soup.webp',
        favorite: false,
        categoryId: 2,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([40, 4, 31]),
        todoList: '1) Тыкву очистить и нарезать кубиками.\n2) Лук нарезать кубиками.\n3) Обжарить лук на сковороде.\n4) Добавить тыкву и залить бульоном или водой. Варить до мягкости тыквы.\n5) Взбить суп блендером до однородной массы. Добавить соль, перец и специи.',
    },
    {
        id: 19,
        name: "Курица с овощами",
        img: routeToImg + 'chicken_with_veg.webp',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([41, 9, 10, 4]),
        todoList: '1) Курицу нарезать кубиками.\n2) Картофель, морковь и лук нарезать кубиками.\n3) Обжарить курицу на сковороде.\n4) Добавить овощи и тушить до готовности. Добавить соль, перец и специи.',
    },
    {
        id: 20,
        name: "Салат Греческий",
        img: routeToImg + 'greek_salad.webp',
        favorite: false,
        categoryId: 1,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 2,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([42, 43, 44, 45]),
        todoList: '1) Огурцы, помидоры, перец и лук нарезать кубиками.\n2) Сыр фета нарезать кубиками.\n3) Смешать все ингредиенты. Добавить оливки и заправить оливковым маслом. Добавить соль, перец и орегано.',
    },
    {
        id: 21,
        name: "Паста Карбонара",
        img: routeToImg + 'pasta_carbonara.jpg',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([46, 47, 0, 48]),
        todoList: '1) Пасту отварить до состояния аль денте.\n2) Бекон нарезать кубиками и обжарить на сковороде.\n3) Яйца взбить с сыром пармезан, солью и перцем.\n4) Смешать пасту с беконом и яичной смесью. Подавать горячим.',
    },
    {
        id: 22,
        name: "Пицца Маргарита",
        img: routeToImg + 'pizza_margarita.webp',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([49, 50, 51, 52]),
        todoList: '1) Приготовить тесто для пиццы.\n2) Смазать тесто томатным соусом.\n3) Выложить нарезанные помидоры и моцареллу.\n4) Посыпать базиликом и запекать в духовке до готовности.',
    },
    {
        id: 23,
        name: "Яичница с беконом",
        img: routeToImg + 'fried_eggs_bacon.webp',
        favorite: false,
        categoryId: 1,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 1,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([0, 47]),
        todoList: '1) Бекон нарезать и обжарить на сковороде.\n2) Вылить яйца на сковороду.\n3) Жарить до готовности.',
    },
        {
        id: 24,
        name: "Каша манная",
        img: routeToImg + 'mannaya.jpg',
        favorite: false,
        categoryId: 1,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 1,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([53, 31]),
        todoList: '1) Молоко довести до кипения.\n2) Всыпать манную крупу тонкой струйкой, постоянно помешивая.\n3) Варить на медленном огне до загустения, помешивая.',
    },
    {
        id: 25,
        name: "Запеченные яблоки с корицей",
        img: routeToImg + 'baked_apples.webp',
        favorite: false,
        categoryId: 5,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 5,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([39, 54, 55]),
        todoList: '1) Яблоки вымыть, вырезать сердцевину.\n2) Смешать мед с корицей и начинить яблоки.\n3) Запекать в духовке до мягкости.',
    },
    {
        id: 26,
        name: "Суп харчо",
        img: routeToImg + 'soup_harcho.webp',
        favorite: false,
        categoryId: 2,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 3,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 3,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([17, 20, 56, 57]),
        todoList: '1) Мясо отварить до готовности.\n2) Рис промыть.\n3) В бульон добавить рис, томатную пасту, чеснок, грецкие орехи, соль, перец и специи.\n4) Варить до готовности риса.',
    },
    {
        id: 27,
        name: "Салат крабовый",
        img: routeToImg + 'crab_salad.webp',
        favorite: false,
        categoryId: 1,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 2,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([58, 9, 0, 16]),
        todoList: '1) Крабовые палочки нарезать кубиками.\n2) Яйца отварить и нарезать кубиками.\n3) Смешать крабовые палочки, яйца, кукурузу и майонез.',
    },
    {
        id: 28,
        name: "Пельмени",
        img: routeToImg + 'pelmeni.webp',
        favorite: false,
        categoryId: 2,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([59, 0, 4]),
        todoList: '1) Пельмени отварить в кипящей воде до готовности.',
    },
    {
        id: 29,
        name: "Сырный суп",
        img: routeToImg + 'cheese_soup.webp',
        favorite: false,
        categoryId: 2,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([60, 9, 4]),
        todoList: '1) Картофель нарезать кубиками и отварить в воде.\n2) Добавить плавленый сыр и варить до его растворения.\n3) Добавить обжаренный лук и морковь. Добавить соль, перец и специи.',
    },
    {
        id: 30,
        name: "Оладьи",
        img: routeToImg + 'oladi.webp',
        favorite: false,
        categoryId: 1,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 1,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([0, 6, 11, 61]),
        todoList: '1) Яйца взбить с сахаром и солью.\n2) Добавить кефир или простоквашу. Перемешать.\n3) Добавить муку и разрыхлитель. Перемешать.\n4) Жарить на разогретой сковороде с обеих сторон до золотистого цвета.',
    },
   {
        id: 31,
        name: "Бефстроганов",
        img: routeToImg + 'beefstraganoff.webp',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([62, 4, 63]),
        todoList: '1) Мясо нарезать тонкими полосками.\n2) Лук нарезать полукольцами и обжарить.\n3) Добавить мясо и обжарить до золотистого цвета.\n4) Добавить сметану и томатную пасту. Тушить на медленном огне до готовности.',
    },
     {
        id: 32,
        name: "Морковный торт",
        img: routeToImg + 'carrot_cake.webp',
        favorite: false,
        categoryId: 5,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 5,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 3,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 3,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([16, 6, 0, 64]),
        todoList: '1) Морковь натереть на мелкой терке.\n2) Яйца взбить с сахаром.\n3) Добавить муку, корицу, разрыхлитель, грецкие орехи и морковь. Перемешать.\n4) Вылить тесто в форму для запекания и запекать в духовке до готовности.',
    },
    {
        id: 33,
        name: "Салат Цезарь",
        img: routeToImg + 'tsezar.jpg',
        favorite: false,
        categoryId: 1,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 2,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([101, 102, 103, 104, 105]),
        todoList: '1) Нарезать листья салата. 2) Обжарить куриную грудку. 3) Приготовить соус. 4) Смешать все ингредиенты.'
    },
    {
        id: 34,
        name: "Тирамису",
        img: routeToImg + 'tiramisu.jpg',
        favorite: false,
        categoryId: 5,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 3,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([106, 107, 108, 109, 110]),
        todoList: '1) Приготовить кофейную пропитку. 2) Сделать крем из маскарпоне. 3) Собрать десерт слоями. 4) Охладить 4 часа.'
    },
    {
        id: 35,
        name: "Мохито",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 4,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 5,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([4, 128, 1, 50, 213]),
        todoList: "Смешать все ингредиенты в бокале, добавить лёд.",
    },
    {
        id: 36,
        name: "Глинтвейн",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 4,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([216, 1, 60, 54]),
        todoList: "Нагреть вино с сахаром и специями, не доводя до кипения.",
    },
    {
        id: 37,
        name: "Какао",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 4,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 1,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([3, 1, 20, 27]),
        todoList: "Вскипятить молоко, добавить какао и сахар, размешать.",
    },
    {
        id: 38,
        name: "Смузи с бананом",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 4,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 1,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([100, 3, 112, 72]),
        todoList: "Взбить все ингредиенты в блендере.",
    },
    {
        id: 39,
        name: "Лимонный чай",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 4,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 5,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([4, 127, 1, 22]),
        todoList: "Заварить чай, добавить лимон и сахар.",
    },
    {
        id: 40,
        name: "Кофе по-венски",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 4,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 1,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([107, 27, 109]),
        todoList: "Взбить сливки, добавить в кофе, посыпать какао.",
    },
    {
        id: 41,
        name: "Ягодный морс",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 4,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 5,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([4, 131, 1]),
        todoList: "Вскипятить воду с ягодами и сахаром, процедить.",
    },
    {
        id: 42,
        name: "Молочный коктейль",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 4,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 5,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([3, 1, 106, 20]),
        todoList: "Взбить все ингредиенты в блендере.",
    },
    {
        id: 43,
        name: "Имбирный чай",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 4,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 5,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([4, 205, 1, 127]),
        todoList: "Заварить чай с имбирём, добавить лимон и сахар.",
    },
    {
        id: 44,
        name: "Шоколадный молочный коктейль",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 4,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 5,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([3, 1, 20, 106]),
        todoList: "Взбить все ингредиенты в блендере.",
    },
    {
        id: 45,
        name: "Жаркое",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 2,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([37, 101, 34, 5]),
        todoList: "Обжарить курицу с луком, добавить картофель и тушить до готовности.",
    },
    {
        id: 46,
        name: "Картофель по-деревенски",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([37, 5, 2, 58]),
        todoList: "Нарезать картофель, смешать с маслом и специями, запечь до золотистой корочки.",
    },
    {
        id: 47,
        name: "Голубцы",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 2,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 3,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([39, 101, 8, 34]),
        todoList: "Завернуть фарш с рисом в капустные листья, тушить в соусе до готовности.",
    },
    {
        id: 48,
        name: "Фаршированный перец",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 2,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([42, 101, 8, 34]),
        todoList: "Нафаршировать перцы мясом с рисом, тушить в соусе до готовности.",
    },
    {
        id: 49,
        name: "Лазанья",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 2,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 3,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([14, 26, 41, 15]),
        todoList: "Слоить листы лазаньи с соусом и сыром, запечь в духовке.",
    },
    {
        id: 50,
        name: "Рататуй",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([41, 43, 42, 45]),
        todoList: "Нарезать овощи кружочками, выложить в форму и запечь.",
    },
    {
        id: 51,
        name: "Курица в сливочном соусе",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([101, 23, 34, 5]),
        todoList: "Обжарить курицу с луком, добавить сливки и тушить до готовности.",
    },
    {
        id: 52,
        name: "Рыба в кляре",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([97, 0, 6, 5]),
        todoList: "Обмакнуть рыбу в кляр, обжарить на масле до золотистой корочки.",
    },
    {
        id: 53,
        name: "Гречка с грибами",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([9, 48, 34, 5]),
        todoList: "Обжарить грибы с луком, добавить гречку и воду, варить до готовности.",
    },
    {
        id: 54,
        name: "Рис с овощами",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([8, 41, 42, 5]),
        todoList: "Обжарить овощи, добавить рис и воду, варить до готовности.",
    },
    {
        id: 55,
        name: "Сэндвич с курицей",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 1,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 1,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([14, 101, 102, 31]),
        todoList: "Собрать сэндвич из хлеба, курицы, салата и майонеза.",
    },
    {
        id: 56,
        name: "Окрошка",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 2,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 2,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([4, 6, 40, 46, 31]),
        todoList: "Нарезать все ингредиенты, залить квасом, добавить сметану.",
    },
    {
        id: 57,
        name: "Картофельные зразы",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 2,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([37, 101, 0, 6]),
        todoList: "Приготовить картофельное пюре, сформировать зразы с начинкой, обжарить.",
    },
    {
        id: 58,
        name: "Клубничный мусс",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 5,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 3,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([131, 1, 71]),
        todoList: "Взбить клубнику с сахаром, добавить желатин, охладить.",
    },
    {
        id: 59,
        name: "Гаспачо",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 2,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 2,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([41, 42, 128, 45]),
        todoList: "Измельчить все ингредиенты в блендере, охладить.",
    },
    {
        id: 60,
        name: "Куриные наггетсы",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 1,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([101, 0, 6, 5]),
        todoList: "Обвалять кусочки курицы в муке, яйце и панировке, обжарить.",
    },
    {
        id: 61,
        name: "Шоколадные маффины",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 5,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 3,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 2,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([0, 1, 20, 6]),
        todoList: "Смешать все ингредиенты, разлить по формам, выпекать 20-25 минут.",
    },
    {
        id: 62,
        name: "Спагетти с сыром",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([14, 26, 5]),
        todoList: "Отварить спагетти, смешать с сыром и маслом.",
    },
    {
        id: 63,
        name: "Фруктовый лёд",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 5,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 3,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 1,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([131, 1, 4]),
        todoList: "Смешать ингредиенты, разлить по формочкам, заморозить.",
    },
    {
        id: 64,
        name: "Овощное рагу",
        img: routeToImg + 'default-recipe.png',
        favorite: false,
        categoryId: 3,
        category: function() { return getCategory(this.categoryId) },
        eatingTimeId: 4,
        eatingTime: function() { return getEatingTime(this.eatingTimeId) },
        cookingTimeId: 2,
        cookingTime: function() { return getCookingTime(this.cookingTimeId)},
        difficultyId: 1,
        difficulty: function() { return getDifficulty(this.difficultyId) },
        ingredients: getCopiedIngredientsByIds([37, 41, 42, 5]),
        todoList: "Обжарить овощи по очереди, добавить специи, тушить до готовности.",
    }
]